# This workflow will check that the code runs for many different operating systems

name: Operating Systems

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
    - uses: actions/checkout@v4      #says to checkout the repository to the place where the runner is operating
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |      
        python -m pip install .[dev]                             
    - name: Lint with flake8
      run: |
        flake8                                                  
    - name: Test with pytest
      run: |
        pytest                                                 

        